name: Deploy the DNS configration

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      test: ${{ secrets.TEST_SECRET }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: setup DNS control
        run: |
          cd $PWD
          wget -q https://github.com/StackExchange/dnscontrol/releases/download/v4.8.2/dnscontrol_4.8.2_linux_amd64.tar.gz
          tar -zxvf dnscontrol_4.8.2_linux_amd64.tar.gz
          chmod +x dnscontrol

      - name: ErrorCheck
        run: ./dnscontrol --no-colors=true check

      - name: Deploy
        run: ./dnscontrol--no-colors=true push

  error_notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: ${{ failure() }}
    steps:
      - name: Send GitHub Action trigger data to Slack workflow
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "Github actions build failed! <${{ github.server_url }}/${{ github.repository }}|${{ github.event.repository.name }}>のビルドが失敗しました。\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|対象のrun>お確認し、対応着手時・完了後は、本チャンネルにて経緯を報告ください。"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_ALERT_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

