name: Build and release on GitHub

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: get pdw
        run: pwd

      - name: get tag name
        shell: python
        run: |
          import os
          import glob
          print(os.getcwd())
          print(glob.glob(""))
