name: Build and release on GitHub

on:
  push:
    tags: 
      - "*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: get tag name
        run: echo TAG_NAME=$($GITHUB_REF -replace 'refs/tags/', '') >> $GITHUB_ENV

      - name: echo tag name
        run: |
          echo "${TAG_NAME}"
          echo "${{ env.TAG_NAME }}"