name: Build and release on GitHub

on:
  push:
    tags: 
      - "*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4


      - name: set tag name
      run: |
        echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: show tag varibles
        run: echo ${TAG_NAME}
