name: Build and release on GitHub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: test
        run: echo ${GITHUB_EVENT_PATH}

