name: check for pull request into master

on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: setup DNS control
        run: |
          cd $PWD
          wget -q https://github.com/StackExchange/dnscontrol/releases/download/v4.8.2/dnscontrol_4.8.2_linux_amd64.tar.gz
          tar -zxvf dnscontrol_4.8.2_linux_amd64.tar.gz
          chmod +x dnscontrol

      - name: errorCheck
        run: ./dnscontrol check

      - name: preview
        run: ./dnscontrol preview | tee preview_result.txt

      - name: comment_preview
        env:
          GH_TOKEN: ${{ github.token }}
        run: cat preview_result.txt | gh pr comment ${{ github.event.pull_request.number }} -F -
