name: check for pull request into master

on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: errorCheck
        uses: koenrh/dnscontrol-action@v3
        with:
          args: check

      - name: preview
        uses: koenrh/dnscontrol-action@v3
        id: dnscontrol_preview
        with:
          args: preview

      - name: comment_preview
        run: gh pr comment -B "${{ steps.dnscontrol_preview.outputs.preview_comment }}"