name: check for pull request into master

on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    runs-on: ubuntu-latest
    env:
      test: ${{ secrets.TEST_SECRET }}
    container:
      image: ghcr.io/stackexchange/dnscontrol:latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: errorCheck
        run: dnscontrol check

      - name: preview
        run: |
          dnscontrol preview | tee "preview.txt"
